language: objective-c
osx_image: xcode7
xcode_workspace: FHAuthDemo.xcworkspace
xcode_scheme: FHAuthDemo
xcode_sdk: iphonesimulator

before_install:
    - gem install cocoapods -N --no-rdoc --no-ri --no-document --quiet

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master